.\" -*- mode: troff; coding: utf-8 -*-
.\"*******************************************************************
.\"
.\" This file was extracted from hal/components/conv_u64_s64.comp using halcompile.g.
.\" Modify the source file.
.\"
.\"*******************************************************************

.TH CONV_U64_S64 "9" "2025-05-27" "LinuxCNC Documentation" "HAL Component"
.SH NAME

conv_u64_s64 \- Convert a value from u64 to s64
.SH SYNOPSIS
.HP
.B loadrt conv_u64_s64 [count=\fIN\fB|names=\fIname1\fB[,\fIname2...\fB]]
.SH FUNCTIONS
.TP
\fBconv-u64-s64.\fIN\fB\fR
Update 'out' based on 'in'
.SH PINS
.TP
.B conv-u64-s64.\fIN\fB.in\fR u64 in \fR
.br
.ns
.TP
.B conv-u64-s64.\fIN\fB.out\fR s64 out \fR
.br
.ns
.TP
.B conv-u64-s64.\fIN\fB.out-of-range\fR bit out \fR
TRUE when 'in' is not in the range of s64
.SH PARAMETERS
.TP
.B conv-u64-s64.\fIN\fB.clamp\fR bit rw \fR
If TRUE, then clamp to the range of s64.  If FALSE, then allow the value to "wrap around".
.SH AUTHOR

Jeff Epler
.SH LICENSE

GPL
