.\" -*- mode: troff; coding: utf-8 -*-
.\"*******************************************************************
.\"
.\" This file was extracted from hal/components/not.comp using halcompile.g.
.\" Modify the source file.
.\"
.\"*******************************************************************

.TH NOT "9" "2025-05-27" "LinuxCNC Documentation" "HAL Component"
.SH NAME

not \- Inverter
.SH SYNOPSIS
.HP
.B loadrt not [count=\fIN\fB|names=\fIname1\fB[,\fIname2...\fB]]
.SH FUNCTIONS
.TP
\fBnot.\fIN\fB\fR

.SH PINS
.TP
.B not.\fIN\fB.in\fR bit in \fR
.br
.ns
.TP
.B not.\fIN\fB.out\fR bit out \fR
.SH SEE ALSO


\fBand2\fR(9),
\fBlogic\fR(9),
\fBlut5\fR(9),
\fBor2\fR(9),
\fBxor2\fR(9).

.SH AUTHOR

Jeff Epler
.SH LICENSE

GPL
