.\" -*- mode: troff; coding: utf-8 -*-
.\"*******************************************************************
.\"
.\" This file was extracted from hal/components/xyzbca_trsrn.comp using halcompile.g.
.\" Modify the source file.
.\"
.\"*******************************************************************

.TH XYZBCA_TRSRN "9" "2025-05-27" "LinuxCNC Documentation" "HAL Component"
.SH NAME

xyzbca_trsrn \- Switchable kinematics for 6 axis machine with a rotary table B, rotary spindle C and nutating spindle A
.SH SYNOPSIS
.HP
.B loadrt xyzbca_trsrn [count=\fIN\fB|names=\fIname1\fB[,\fIname2...\fB]]
.SH DESCRIPTION


.if \n[.g] .mso www.tmac



.SH FUNCTIONS
.TP
\fBxyzbca-trsrn.\fIN\fB.fdemo\fR (requires a floating-point thread)

.SH PINS
.TP
.B xyzbca-trsrn.\fIN\fB.fpin\fR s32 out \fR(default: \fI0\fR)
pin to demonstrate use of a conventional (non-kinematics) function fdemo
.SH AUTHOR

David Mueller
.SH LICENSE

GPL
