'\" t
.\"     Title: gs2_vfd
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 05/27/2025
.\"    Manual: LinuxCNC Documentation
.\"    Source: LinuxCNC
.\"  Language: English
.\"
.TH "GS2_VFD" "1" "05/27/2025" "LinuxCNC" "LinuxCNC Documentation"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
gs2_vfd \- HAL non\-realtime component for Automation Direct GS2 VFDs
.SH "SYNOPSIS"
.sp
\fBgs2_vfd\fR [OPTIONS]
.SH "DESCRIPTION"
.sp
This manual page explains the \fBgs2_vfd\fR component\&. This component reads and writes to the GS2 via a modbus connection\&.
.sp
\fBgs2_vfd\fR is for use with LinuxCNC\&.
.SH "OPTIONS"
.PP
\-b, \-\-bits \fIn\fR
.RS 4
Set number of data bits to
\fIn\fR, where
\fIn\fR
must be from 5 to 8 inclusive (default 8)\&.
.RE
.PP
\-d, \-\-device \fIpath\fR
.RS 4
Set the path to the file representing the serial device to use (default /dev/ttyS0)\&.
.RE
.PP
\-v, \-\-verbose
.RS 4
Turn on verbose mode\&.
.RE
.PP
\-g, \-\-debug
.RS 4
Turn on debug messages\&. Note that if there are serial errors, this may become annoying\&. Debug mode will cause all modbus messages to be printed in hex on the terminal\&.
.RE
.PP
\-n, \-\-name \fIstring\fR
.RS 4
Set the name of the HAL module\&. The HAL comp name will be set to
\fIstring\fR, and all pin and parameter names will begin with
\fIstring\fR
(default gs2_vfd)\&.
.RE
.PP
\-p, \-\-parity [even,odd,none]
.RS 4
Set serial parity to even, odd, or none (default odd)\&.
.RE
.PP
\-r, \-\-rate n
.RS 4
Set baud rate to
\fIn\fR\&. It is an error if the rate is not one of the following: 110, 300, 600, 1200, 2400, 4800, 9600, 19200, 38400, 57600, 115200 (default 38400)\&.
.RE
.PP
\-s, \-\-stopbits [1,2]
.RS 4
Set serial stop bits to 1 or 2 (default 1)\&.
.RE
.PP
\-t, \-\-target <n>
.RS 4
Set MODBUS target (slave) number\&. This must match the device number you set on the GS2 (default 1)\&.
.RE
.PP
\-A, \-\-accel\-seconds <n>
.RS 4
Seconds to accelerate the spindle from 0 to Max RPM (default 10\&.0)\&.
.RE
.PP
\-D, \-\-decel\-seconds <n>
.RS 4
Seconds to decelerate the spindle from Max RPM to 0\&. If set to 0\&.0 the spindle will be allowed to coast to a stop without controlled deceleration (default 0\&.0)\&.
.RE
.PP
\-R, \-\-braking\-resistor
.RS 4
This argument should be used when a braking resistor is installed on the GS2 VFD (see Appendix A of the GS2 manual)\&. It disables deceleration over\-voltage stall prevention (see GS2 modbus Parameter 6\&.05), allowing the VFD to keep braking even in situations where the motor is regenerating high voltage\&. The regenerated voltage gets safely dumped into the braking resistor\&.
.RE
.SH "PINS"
.PP
<name>\&.DC\-bus\-volts (float, out)
.RS 4
from the VFD
.RE
.PP
<name>\&.at\-speed (bit, out)
.RS 4
when drive is at commanded speed
.RE
.PP
<name>\&.err\-reset (bit, in)
.RS 4
reset errors sent to VFD
.RE
.PP
<name>\&.firmware\-revision (s32, out)
.RS 4
from the VFD
.RE
.PP
<name>\&.frequency\-command (float, out)
.RS 4
from the VFD
.RE
.PP
<name>\&.frequency\-out (float, out)
.RS 4
from the VFD
.RE
.PP
<name>\&.is\-stopped (bit, out)
.RS 4
when the VFD reports 0 Hz output
.RE
.PP
<name>\&.load\-percentage (float, out)
.RS 4
from the VFD
.RE
.PP
<name>\&.motor\-RPM (float, out)
.RS 4
from the VFD
.RE
.PP
<name>\&.output\-current (float, out)
.RS 4
from the VFD
.RE
.PP
<name>\&.output\-voltage (float, out)
.RS 4
from the VFD
.RE
.PP
<name>\&.power\-factor (float, out)
.RS 4
from the VFD
.RE
.PP
<name>\&.scale\-frequency (float, out)
.RS 4
from the VFD
.RE
.PP
<name>\&.speed\-command (float, in)
.RS 4
speed sent to VFD in RPM\&. It is an error to send a speed faster than the Motor Max RPM as set in the VFD\&.
.RE
.PP
<name>\&.spindle\-fwd (bit, in)
.RS 4
1 for FWD and 0 for REV sent to VFD
.RE
.PP
<name>\&.spindle\-on (bit, in)
.RS 4
1 for ON and 0 for OFF sent to VFD, only on when running
.RE
.PP
<name>\&.spindle\-rev (bit, in)
.RS 4
1 for ON and 0 for OFF, only on when running
.RE
.PP
<name>\&.status\-1 (s32, out)
.RS 4
Drive Status of the VFD (see the GS2 manual)
.RE
.PP
<name>\&.status\-2 (s32, out)
.RS 4
Drive Status of the VFD (see the GS2 manual) Note that the value is a sum of all the bits that are on\&. So a 163 which means the drive is in the run mode is the sum of 3 (run) + 32 (freq set by serial) + 128 (operation set by serial)\&.
.RE
.SH "PARAMETERS"
.PP
<name>\&.error\-count (s32, RW), <name>\&.loop\-time (float, RW)
.RS 4
how often the modbus is polled (default 0\&.1)
.RE
.PP
<name>\&.nameplate\-HZ (float, RW)
.RS 4
Nameplate Hz of motor (default 60)
.RE
.PP
<name>\&.nameplate\-RPM (float, RW)
.RS 4
Nameplate RPM of motor (default 1730)
.RE
.PP
<name>\&.retval (s32, RW)
.RS 4
the return value of an error in HAL
.RE
.PP
<name>\&.tolerance (float, RW)
.RS 4
speed tolerance (default 0\&.01)
.RE
.PP
<name>\&.ack\-delay (s32, RW)
.RS 4
number of read/write cycles before checking at\-speed (default 2)
.RE
.SH "SEE ALSO"
.sp
\fIGS2 Driver\fR in the LinuxCNC documentation for a full description of the \fBGS2\fR syntax
.sp
\fIGS2 Examples\fR in the LinuxCNC documentation for examples using the \fBGS2\fR component
.SH "AUTHOR"
.sp
John Thornton
.SH "LICENSE"
.sp
GPL
