'\" t
.\"     Title: qtplasmac-materials
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 05/27/2025
.\"    Manual: LinuxCNC Documentation
.\"    Source: LinuxCNC
.\"  Language: English
.\"
.TH "QTPLASMAC\-MATERIALS" "1" "05/27/2025" "LinuxCNC" "LinuxCNC Documentation"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
qtplasmac-materials \- Create a plasma materials file\&.
.SH "SYNOPSIS"
.sp
\fBqtplasmac\-materials\fR
.SH "DESCRIPTION"
.sp
qtplasmac\-materials is a Python script for creating a materials file\&.
.sp
The file can be created by text entry or by importing text from a CAM tool file\&.
.SH "SEE ALSO"
.sp
See the QtPlasmaC section of the LinuxCNC Documentation for more information\&.
.sp
https://linuxcnc\&.org/docs/devel/html/plasma/qtplasmac\&.html#_material_converter
.SH "AUTHOR"
.sp
Phillip Carter & Gregory D Carl
.SH "LICENSE"
.sp
GPL
