'\" t
.\"     Title: shuttle
.\"    Author: [FIXME: author] [see http://www.docbook.org/tdg5/en/html/author]
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 05/27/2025
.\"    Manual: LinuxCNC Documentation
.\"    Source: LinuxCNC
.\"  Language: English
.\"
.TH "SHUTTLE" "1" "05/27/2025" "LinuxCNC" "LinuxCNC Documentation"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
shuttle \- control HAL pins with the ShuttleXpress, ShuttlePRO, and ShuttlePRO2 device made by Contour Design
.SH "SYNOPSIS"
.sp
\fBloadusr shuttle\fR [\fIDEVICE\fR \&...]
.SH "DESCRIPTION"
.sp
Shuttle is a non\-realtime HAL component that interfaces Contour Design\(cqs ShuttleXpress, ShuttlePRO, and ShuttlePRO2 devices with LinuxCNC\(cqs HAL\&.
.sp
If the driver is started without command\-line arguments, it will probe all /dev/hidraw* device files for Shuttle devices, and use all devices found\&. If it is started with command\-line arguments, it will only probe the devices specified\&.
.sp
The ShuttleXpress has five momentary buttons, a 10 counts/revolution jog wheel with detents, and a 15\-position spring\-loaded outer wheel that returns to center when released\&.
.sp
The ShuttlePRO has 13 momentary buttons, a 10 counts/revolution jog wheel with detents, and a 15\-position spring\-loaded outer wheel that returns to center when released\&.
.sp
The ShuttlePRO2 has 15 momentary buttons, a 10 counts/revolution jog wheel with detents, and a 15\-position spring\-loaded outer wheel that returns to center when released\&.
.SH "UDEV"
.sp
The shuttle driver needs read permission to the Shuttle devices\*(Aq /dev/hidraw* device files\&. This can be accomplished by adding a file \fB/etc/udev/rules\&.d/99\-shuttle\&.rules\fR, with the following contents:
.sp
.if n \{\
.RS 4
.\}
.nf
SUBSYSTEM=="hidraw", ATTRS{idVendor}=="0b33",
ATTRS{idProduct}=="0020", MODE="0444"

SUBSYSTEM=="hidraw", ATTRS{idVendor}=="05f3",
ATTRS{idProduct}=="0240", MODE="0444"

SUBSYSTEM=="hidraw", ATTRS{idVendor}=="0b33",
ATTRS{idProduct}=="0030", MODE="0444"
.fi
.if n \{\
.RE
.\}
.sp
The LinuxCNC Debian package installs an appropriate udev file automatically, but if you are building LinuxCNC from source and are not using the Debian packaging, you\(cqll need to install this file by hand\&. If you install the file by hand you\(cqll need to tell udev to reload its rules files by running udevadm control \-\-reload\-rules\&.
.SH "A WARNING ABOUT THE JOG WHEEL"
.sp
The Shuttle devices have an internal 8\-bit counter for the current jog\-wheel position\&. The shuttle driver can not know this value until the Shuttle device sends its first event\&. When the first event comes into the driver, the driver uses the device\(cqs reported jog\-wheel position to initialize counts to 0\&. This means that if the first event is generated by a jog\-wheel move, that first move will be lost\&.
.sp
Any user interaction with the Shuttle device will generate an event, informing the driver of the jog\-wheel position\&. So if you (for example) push one of the buttons at startup, the jog\-wheel will work fine and notice the first click\&.
.SH "PINS"
.sp
All HAL pin names are prefixed with shuttle followed by the index of the device (the order in which the driver found them), for example shuttle\&.0 or huttle\&.2\&.
.PP
\fI(prefix)\&.button\-(number)\fR (bit out), \fI(prefix)\&.button\-(number)\-not\fR (bit out)
.RS 4
The momentary buttons\&. "(number)" identifies which button corresponds to the HAL pin\&. The "button\-(number)" pins are True when the button is pushed, the "button\-(number)\-not" pins are True when the button is not pushed\&.
.RE
.PP
\fI(prefix)\&.counts\fR (s32 out)
.RS 4
Accumulated counts from the jog wheel (the inner wheel)\&.
.RE
.PP
\fI(prefix)\&.spring\-wheel\-s32\fR (s32 out)
.RS 4
The current deflection of the spring\-wheel (the outer wheel)\&. It\(cqs 0 at rest, and ranges from \-7 at the counter\-clockwise extreme to +7 at the clockwise extreme\&.
.RE
.PP
\fI(prefix)\&.spring\-wheel\-f\fR (float out)
.RS 4
The current deflection of the spring\-wheel (the outer wheel)\&. It\(cqs 0\&.0 at rest, \-1\&.0 at the counter\-clockwise extreme, and +1\&.0 at the clockwise extreme\&. (The Shuttle devices report the spring\-wheel position as an integer from \-7 to +7, so this pin reports only 15 discrete values in its range\&.)
.RE
