'\" t
.\"     Title: svd-ps_vfd
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 05/27/2025
.\"    Manual: LinuxCNC Documentation
.\"    Source: LinuxCNC
.\"  Language: English
.\"
.TH "SVD\-PS_VFD" "1" "05/27/2025" "LinuxCNC" "LinuxCNC Documentation"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
svd-ps_vfd \- HAL non\-realtime component for SVD\-P(S) VFDs
.SH "SYNOPSIS"
.sp
\fBsvd\-ps_vfd\fR [\fIOPTIONS\fR]
.SH "DESCRIPTION"
.sp
The svd\-ps_vfd component interfaces a Soyan Power SVD\-P(S) VFD to the LinuxCNC HAL\&. The VFD is connected via RS\-485 to the LinuxCNC computer\&.
.sp
The SVD\-P(S) VFDs are also sold under the LAPOND brand\&.
.SH "HARDWARE SETUP"
.sp
The SVD\-P(S) VFDs do not come with a Modbus daughterboard by default, it needs to be purchased separately\&.
.SH "FIRMWARE SETUP"
.sp
The sad\-ps_vfd component uses standard Modbus protocol communication, which requires that one parameter be changed from the default settings:
.sp
PD\-05 = 1 (Standard Modbus protocol)
.sp
The following settings have been tested successfully and are the default per Soyans documentation:
.sp
PD\-00 = 6005 (9600 baud)
.sp
PD\-01 = 0 (8N2)
.sp
PD\-02 = 1 (Slave address)
.sp
PD\-03 = 2 (Response delay)
.sp
PD\-04 = 0 (Communication timeout)
.sp
PD\-06 = 0 (Current resolution)
.SH "OPTIONS"
.PP
\fB\-b\fR, \fB\-\-bits\fR \fIN\fR
.RS 4
For Modbus communication, set number of data bits to
\fIN\fR\&.
\fIN\fR
must be between 5 and 8 inclusive\&. (default 8)
\fB\-p\fR,
\fB\-\-parity\fR
[Even,Odd,None] For Modbus communication, set serial parity to Even, Odd, or None\&. (default None)
.RE
.PP
\fB\-r\fR, \fB\-\-rate\fR \fIN\fR
.RS 4
For Modbus communication, set baud rate to
\fIN\fR\&. It is an error if the rate is not one of the following: 1200, 2400, 4800, 9600, 19200, 38400 (default 9600)
.RE
.PP
\fB\-s\fR, \fB\-\-stopbits\fR [1,2]
.RS 4
For Modbus communication set serial stop bits to 1 or 2\&. (default 2)
.RE
.PP
\fB\-t\fR, \fB\-\-target\fR \fIN\fR
.RS 4
For Modbus communication, set Modbus target (slave) number\&. This must match the device number you set on the Huanyang GT VFD\&. (default 1)
.RE
.PP
\fB\-d\fR, \fB\-\-device\fR \fIPATH\fR
.RS 4
For Modbus communication, set the name of the serial device node to use\&. (default /dev/ttyS0)
.RE
.PP
\fB\-v\fR, \fB\-\-verbose\fR
.RS 4
Turn on verbose mode\&.
.RE
.PP
\fB\-S\fR, \fB\-\-motor\-max\-speed\fR \fIRPM\fR
.RS 4
The motor\(cqs max speed in RPM\&.
.RE
.PP
\fB\-F\fR, \fB\-\-max\-frequency\fR \fIHZ\fR
.RS 4
This is the maximum output frequency of the VFD in Hz\&.
.RE
.PP
\fB\-f\fR, \fB\-\-min\-frequency\fR \fIHZ\fR
.RS 4
This is the minimum output frequency of the VFD in Hz\&.
.RE
.SH "PINS"
.PP
\fBsvd\-ps_vfd\&.period\fR (float, in)
.RS 4
The period for the driver\(cqs update cycle, in seconds\&. This is how frequently the driver will wake up, check its HAL pins, and communicate with the VFD\&. Must be between 0\&.001 and 2\&.000 seconds\&. Default: 0\&.1 seconds\&.
.RE
.PP
\fBsvd\-ps_vfd\&.speed\-cmd\fR (float, in)
.RS 4
The requested motor speed, in RPM\&.
.RE
.PP
\fBsvd\-ps_vfd\&.speed\-fb\fR (float, out)
.RS 4
The motor\(cqs current speed, in RPM, reported by the VFD\&.
.RE
.PP
\fBsvd\-ps_vfd\&.at\-speed\fR (bit, out)
.RS 4
True when the drive is on and at the commanded speed (within 2%), False otherwise\&.
.RE
.PP
\fBsvd\-ps_vfd\&.freq\-cmd\fR (float, out)
.RS 4
The requested output frequency, in Hz\&. This is set from the
\&.speed\-cmd
value, and is just shown for debugging purposes\&.
.RE
.PP
\fBsvd\-ps_vfd\&.freq\-fb\fR (float, out)
.RS 4
The current output frequency of the VFD, in Hz\&. This is reported from the VFD to the driver\&.
.RE
.PP
\fBsvd\-ps_vfd\&.spindle\-on\fR (bit, in)
.RS 4
Set this pin True to command the spindle on, at the speed requested on the
\&.speed\-cmd
pin\&. Set this pin False to command the spindle off\&.
.RE
.PP
\fBsvd\-ps_vfd\&.output\-voltage\fR (float, out)
.RS 4
The voltage that the VFD is current providing to the motor, in Volts\&.
.RE
.PP
\fBsvd\-ps_vfd\&.output\-current\fR (float, out)
.RS 4
The current that the motor is currently drawing from the VFD, in Amperes\&.
.RE
.PP
\fBhsvd\-ps_vfd\&.output\-power\fR (float, out)
.RS 4
The power that the motor is currently drawing from the VFD, in Watts\&.
.RE
.PP
\fBsvd\-ps_vfd\&.dc\-bus\-voltage\fR (float, out)
.RS 4
The current voltage of the VFD\(cqs internal DC power supply, in Volts\&.
.RE
.PP
\fBsvd\-ps_vfd\&.modbus\-errors\fR (u32, out)
.RS 4
A count of the number of modbus communication errors between the driver and the VFD\&. The driver is resilient against communication errors, but a large or growing number here indicates a problem that should be investigated\&.
.RE
.PP
\fBsvd\-ps_vfd\&.input\-terminal\fR (float, out)
.RS 4
The VFD\(cqs input terminal register\&.
.RE
.PP
\fBsvd\-ps_vfd\&.AI1\fR (float, out)
.RS 4
The VFD\(cqs AI1 register\&.
.RE
.PP
\fBsvd\-ps_vfd\&.AI2\fR (float, out)
.RS 4
The VFD\(cqs AI2 register\&.
.RE
.SH "AUTHOR"
.sp
Tinic Uro
.SH "LICENSE"
.sp
GPL\-2\&.0+
